### ISSUE TITLE
Slightly clearer option names

### ISSUE THREAD

**Issue by YohananDiamond** [brenopacheco/vim-hydra#6]
I think some of the options don't have very clear names, and, although the documentation for them specifically is pretty solid, a better naming could help a little bit too. I suggest:

* `foreign_key` -> `persist_on_foreign_keys`
* `feed_key` -> `feed_foreign_keys`

Not sure if these names are the best ones, but it'd be nice to (briefly) describe the behavior in the function name.
Also, I'm not sure how to implement this in a good way since it probably would break existing hydras.

**Comment by brenopacheco** [comment]
Thank you for the suggestions. Maybe renaming is not the best option, perhaps adding a little more information to the documentation? To be fair, I haven't used this plugin for some time and I don't think many people use it. If you want, you can write up something in the docs and I'll be glad to merge the request.

**Comment by YohananDiamond** [comment]
Well, I think the documentation for these options is pretty solid, just the name that is a little bit ambiguous, but it's not a big deal either.
One thing I noticed, though: there's a documentation for `feed_key` (`hydra-feed_key`) but it's not listed on the table of contents in hydra.txt - I'll try making a pull request to fix that
